### ISSUE TITLE
Visuel

### ISSUE THREAD

**Issue by LRimaz** [sorchawalsh/projetgr4#2]
- Améliorer modal
- Couleurs moins éclatantes (tableaux)
- Préciser sélection lignes colonnes
- Eventuellement déplacer les boutons

**Comment by AnteJR** [comment]
Progression actuelle : 
1. Modal amélioré avec sweetalert2
2. Couleurs des tableaux atténuées

À faire : 
1. Préciser la sélection des lignes et des colonnes du tableau (Antoine Klotz)
2. ( **AJOUT** ) Style des boutons : quand aucun n'est sélectionné, tous doivent être en bleu

Probablement à ignorer : 
1. Le placement des boutons, une fois que le bouton "disponible" sera préselectionné et surtout suite à l'intégration d'un guide disponible à tout moment, ne semble pas poser de problème
